/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: reaction105 (https://sketchfab.com/reaction105)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/sioux-quartzite-boulder-esu-kansas-e415ff3ab4c745ee8a6d056159e6740e
Title: Sioux Quartzite Boulder (ESU, Kansas)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Rock(props) {
  const { nodes, materials } = useGLTF('./scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 3.076]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 32.447, 0]} rotation={[-Math.PI / 2, 0, -0.087]}>
            <mesh geometry={nodes['LoRes_Retopo_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[1.642, -4.957, -36.087]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./scene.gltf')
